/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI.SignUp;

import GUI.MainPanel.HomeScreen;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrei
 */
public class LogIn extends javax.swing.JFrame implements LogInPanel.signUpListener, SignUpPanel.registerListener {

    /**
     * Creates new form signUp
     */
    public LogIn() {
        initComponents();
        logInPanel.setListener(this);
        signUpPanel.setListener(this);
    }

    public void switchToPanel(String panelName) {
        java.awt.CardLayout cardLayout = (java.awt.CardLayout) jPanel4.getLayout();
        cardLayout.show(jPanel4, panelName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        logInPanel = new GUI.SignUp.LogInPanel();
        signUpPanel = new GUI.SignUp.SignUpPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/Images/119879-madara-png-file-hd.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(jLabel1);

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new java.awt.CardLayout());
        jPanel4.add(logInPanel, "card2");
        jPanel4.add(signUpPanel, "card3");

        jPanel1.add(jPanel4);

        getContentPane().add(jPanel1);

        setSize(new java.awt.Dimension(1016, 608));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LogIn().setVisible(true);

        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private GUI.SignUp.LogInPanel logInPanel;
    private GUI.SignUp.SignUpPanel signUpPanel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void signUpButtonclick(ActionEvent e) {
        if (e.getActionCommand().equals("Sign Up")) {
            switchToPanel("card3");
        } else if (e.getActionCommand().equals("Log In")) {
            if (logInPanel.validateAccount()) {
                JOptionPane.showMessageDialog(this, "Log In successfull!");
                HomeScreen home = new GUI.MainPanel.HomeScreen();
                home.setUser(logInPanel.getUser().getText());
                home.setVisible(true);
                dispose();

            }

        }
    }

    @Override
    public void buttonsListener(ActionEvent e) {
        if (e.getActionCommand().equals("exit")) {
            switchToPanel("card2");
        } else if (e.getActionCommand().equals("register")) {
            if (signUpPanel.checkSignUp()) {
                JOptionPane.showMessageDialog(this, "Account created successfully!");
                switchToPanel("card2");
            }

        }
    }

}
